# List of Indian market indices and their categories
symbols:

  # ---------------------------
  # Sectorial Indices
  # ---------------------------

  - name: Nifty Auto
    ticker: "^CNXAUTO"
    type: sector

  - name: Nifty Bank
    ticker: "^NSEBANK"
    type: sector

  - name: Nifty Chemicals
    ticker: "^CEX"
    type: sector

  - name: Nifty Financial Services
    ticker: "NIFTY_FIN_SERVICE.NS"
    type: sector

  - name: Nifty Financial Services 25/50
    ticker: "^CNXFIN"
    type: sector

  - name: Nifty Financial Services Ex Bank
    ticker: "FINIETF.NS"
    type: sector

  - name: Nifty FMCG
    ticker: "^CNXFMCG"
    type: sector

  - name: Nifty Healthcare
    ticker: "NIFTY_HEALTHCARE.NS"
    type: sector

  - name: Nifty IT
    ticker: "^CNXIT"
    type: sector

  - name: Nifty Media
    ticker: "^CNXMEDIA"
    type: sector

  - name: Nifty Metal
    ticker: "^CNXMETAL"
    type: sector

  - name: Nifty Pharma
    ticker: "^CNXPHARMA"
    type: sector

  - name: Nifty Private Bank
    ticker: "NIFTYPVTBANK.NS"
    type: sector

  - name: Nifty PSU Bank
    ticker: "^CNXPSUBANK"
    type: sector

  - name: Nifty Realty
    ticker: "^CNXREALTY"
    type: sector

  - name: Nifty Consumer Durables
    ticker: "NIFTY_CONSR_DURBL.NS"
    type: sector

  - name: Nifty Oil and Gas
    ticker: "NIFTY_OIL_AND_GAS.NS"
    type: sector

  - name: Nifty500 Healthcare
    ticker: null
    type: sector

  - name: Nifty MidSmall Financial Services
    ticker: null
    type: sector

  - name: Nifty MidSmall Healthcare
    ticker: null
    type: sector

  - name: Nifty MidSmall IT & Telecom
    ticker: null
    type: sector
